#!/bin/bash
#===============================================================================
# ub-make-ds82-raw - Creates a formatted Microbee DS82 raw file.
# SJK 2010/02/26.
#
# Usage: ub-make-ds82-raw filename
#
# Note: options are used here that will overide the format type given in any
# file extensions!  The verbose level is set to 0 to disable normal
# reporting.  No format confirmation prompting!
#===============================================================================

if [ "$1" = "" ] || [ "$2" != "" ]; then
   name=$(basename $0)
   echo "$name - Creates a formatted Microbee DS82 raw file."
   echo "Usage: $name filename"
   exit 1
fi

ubeedisk \
--disk=format \
--force \
--verbose=0 \
--format=ds82 \
--otype=raw \
--of=$1
