#!/bin/bash
#===============================================================================
# ub-ss80-dsk2raw - Converts a Microbee SS80 CPC-EMU DSK file to a raw file.
# SJK 2010/02/26.
#
# Usage: ub-ss80-dsk2raw input_file output_file
#
# Note: options are used here that will overide the format type given in any
# file extensions!  Prompting for a disk description and the creation of an
# INFO and ERR files are disabled. The verbose level is set to 0 to disable
# normal reporting.
#===============================================================================

if [ "$1" = "" ] || [ "$2" = "" ]; then
   name=$(basename $0)
   echo "$name - Converts a Microbee SS80 CPC-EMU DSK file to a raw file."
   echo "Usage: $name input_file output_file"
   exit 1
fi

ubeedisk \
--info=off \
--verbose=0 \
--format=ss80 \
--itype=dsk \
--if=$1 \
--otype=raw \
--of=$2
